using DataColector.DefaultRealization;
using DataColector.Interfaces;
using DataParser.DefaultRealization;
using DataParser.Interfaces;
using DataSaver.Interfaces;
using DevExpress.XtraBars.Helpers;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;

namespace DXApplication1
{
    public partial class Form1 : XtraForm
    {
        private IDataColector _collector;
        private IDataParser _parser;
        private IDataSaver _saver;
        private List<IDataMatch> dataList;

        private string defUrl = @"https://ua.1xbet.com/LiveFeed/Get1x2?sportId=0&sports=&champId=0&tf=1000000&count=50&cnt=10&lng=ru&cfview=0";

        public Form1()
        {
            InitializeComponent();
            InitSkinGallery();
            // This line of code is generated by Data Source Configuration Wizard
            dataList = new List<IDataMatch>();
            gridControl1.DataSource = dataList;

            _collector = new DefaultDataColector();
            _parser = new DefaultDataParser(new DefaultMatch());
        }

        //public Form1(IDataColector colector, IDataParser parser, IDataSaver saver)
        //    //: this()
        //{
        //    _collector = colector;
        //    _parser = parser;
        //    _saver = saver;
        //    InitializeComponent();
        //    InitSkinGallery();
        //}

        void InitSkinGallery()
        {
            SkinHelper.InitSkinGallery(rgbiSkins, true);
        }

        private void Form_Load(object sender, EventArgs e)
        {
            //var dataTable = _saver.MakeTable(
            //    _parser.ParseData(
            //        _collector.GetJsonArray(defUrl)));
            dataList.AddRange(_parser.ParseData(
                _collector.GetJsonArray(defUrl)));               
            webBrowser1.Navigate("http://positivebet.com/");
        }
    }
}